# Generated by Django 4.0.2 on 2022-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_climate_tilicho'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_tempreture',
            fields=[
                ('created_at', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('field1', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
