# Generated by Django 4.0.2 on 2022-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_sensor_tempreture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_tempreture',
            name='field2',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=6),
            preserve_default=False,
        ),
    ]
