# Generated by Django 4.0.2 on 2022-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_sensor_tempreture_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_tempreture',
            name='entry',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor_tempreture',
            name='created_at',
            field=models.CharField(max_length=40),
        ),
    ]
