# Generated by Django 4.0.2 on 2022-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_sensor_tempreture_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_data',
            fields=[
                ('created_at', models.CharField(max_length=40)),
                ('entry', models.IntegerField(primary_key=True, serialize=False)),
                ('field1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('field2', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='sensor_tempreture',
        ),
    ]
